### ISSUE TITLE
Pumpkin pie is considered a fruit

### ISSUE THREAD

**Issue by SeriousCreeper** [eerussianguy/firmalife#103]
Not entirely sure if this is on purpose or not, but seems a bit odd to me so i'm assuming it's an oversight. 
The pumpkin pie is considered a fruit and can therefore be used in many other recipes, like the drying mat, soups, to make vinegar. 

![pie](https://i.imgur.com/QrijU9n.png)

Firmalife: 1.2.1

**Comment by eerussianguy** [comment]
I don't use the vanilla item in firmalife.

**Comment by SeriousCreeper** [comment]
All i was using is firmalife and tfc, this is the default recipe

**Comment by eerussianguy** [comment]
The firmalife recipe accepts anything tagged as a fruit. It should not be tagged as a fruit in TFC. I don't do anything to the vanilla item in firmalife.
