### ISSUE TITLE
Bees: Phosphorus being capped based on Nitrogen value

### ISSUE THREAD

**Issue by pietro-lopes** [eerussianguy/firmalife#120]
This code line, please check `getNutrient(N)`

https://github.com/eerussianguy/firmalife/blob/75149c67329a5230c27b11c4c7c8b760d4dcc024/src/main/java/com/eerussianguy/firmalife/common/blockentities/FLBeehiveBlockEntity.java#L350-L355

**Comment by eerussianguy** [comment]
fixed
