### ISSUE TITLE
Cheese aging mechanics doesn't seems to be working at all

### ISSUE THREAD

**Issue by pietro-lopes** [eerussianguy/firmalife#121]
Something is odd about this mechanic, can't make them age even in creative using /time add & change ticks speed.
Also playing normally on online server I'm absolutely sure that I let it age >28d, someone also said that let it for weeks and they are still "Fresh"

**Comment by eerussianguy** [comment]
Needs to be in a proper cellar.

**Comment by eerussianguy** [comment]
fixed
