### ISSUE TITLE
Configs for greenhouse

### ISSUE THREAD

**Issue by trainchoo** [eerussianguy/firmalife#122]
Can these values be edited via the config file?
The crops grow too quickly

    public static final float GROWTH_FACTOR = 1f / (16 * ICalendar.TICKS_IN_DAY); // 24 -> 16 days
    public static final float NUTRIENT_CONSUMPTION = 1f / (8 * ICalendar.TICKS_IN_DAY); //  12 -> 8 days
    public static final float WATER_CONSUMPTION = 1f / (12 * ICalendar.TICKS_IN_DAY); // 12 days
    public static final float NUTRIENT_GROWTH_FACTOR = 0.5f;

**Comment by eerussianguy** [comment]
I can make them configurable at some point yeah. I also think they grow a bit too quickly

**Comment by eerussianguy** [comment]
done
