### ISSUE TITLE
Vat recipe for Olive Oil Water got 5x buff and Tomato Sauce got 5x nerf

### ISSUE THREAD

**Issue by pietro-lopes** [eerussianguy/firmalife#123]
Title.

| Recipe                                        | Pot outcome           | Vat outcome                      |
|-----------------------------------------------|-----------------------|----------------------------------|
| 5x Olive Paste + 1B of Water                  | 1B of Olive Oil Water | 5B of Olive Oil Water            |
| Pot: 1 Tomato, 1 Salt, 1 Garlic + 1B of Water | 5x Tomato Sauce       |                                  |
| Vat: 1 Tomato Sauce mix + 1B of Water         |                       | 1 Tomato Sauce + 800 mB of Water |

Great update btw :hugs:

**Comment by eerussianguy** [comment]
just reworked this
