### ISSUE TITLE
Tomato sauce still nerfed on Vat on 1.2.8

### ISSUE THREAD

**Issue by pietro-lopes** [eerussianguy/firmalife#124]
This one, makes 5
![image](https://user-images.githubusercontent.com/97140255/229384439-25afa130-bc00-434b-942c-e33276afe623.png)

This one makes 1

![image](https://user-images.githubusercontent.com/97140255/229384255-1e5b174a-3704-4186-833a-e893c3cb0360.png)
![image](https://user-images.githubusercontent.com/97140255/229384261-3773b2a0-75aa-486c-819d-7dabd2f1a063.png)
*200 mB of water*

Easy fix is to give 5 Tomato sauce mix for tomato + salt + garlic recipe or what you think is the best.

:hugs:

**Comment by eerussianguy** [comment]
done
