### ISSUE TITLE
Drinking chocolate doesn't give you saturation as you are supposed to receive 1 sat

### ISSUE THREAD

**Issue by pietro-lopes** [eerussianguy/firmalife#125]
https://github.com/eerussianguy/firmalife/blob/8320059ca174372c50810d39579838af0be182fd/src/main/resources/data/firmalife/tfc/drinkables/chocolate.json#L1-L10

**Comment by eerussianguy** [comment]
This should apply when u eat your next meal, like milk. Can you check?

**Comment by pietro-lopes** [comment]
I tried the following:

```
/kill @p
/tfc player @p set hunger 4
/tfc player @p query saturation
```
Saturation is 5.0 / 20

- Eats a potato (10% sat, 2 points)
`Saturation is 7.0 / 20`
- Drinks Chocolate
`Saturation is 7.0 / 20`
- Eats a potato
`Saturation is 9.0 / 20`
- Drinks Chocolate
`Saturation is 9.0 / 20`
- Eats a potato
`Saturation is 11.0 / 20`
- Drinks Chocolate
`Saturation is 11.0 / 20`
- Eats a potato
`Saturation is 13.0 / 20`
- Drinks Chocolate
`Saturation is 13.0 / 20`

**Comment by eerussianguy** [comment]
OK, so this is a byproduct of how TFC handles zero hunger foods, so it's a TFC issue, not a FIrmalife issue. I'm not gonna open an issue right away so I can consult with alcatraz.
