### ISSUE TITLE
latest oven textures seem to be missing

### ISSUE THREAD

**Issue by FoilHatGuy** [eerussianguy/firmalife#129]
Textures on oven blocks are missing despite them existing in assets/firmalife/models/block

![image](https://github.com/eerussianguy/firmalife/assets/46861008/652e55f4-b6b1-4d23-8ac7-aa374db46e98)
![image](https://github.com/eerussianguy/firmalife/assets/46861008/10609a13-bfc3-49fa-aac3-dfd9f211e00d)

P.S. Might be invalid issue due to firmalife being installed as a part of SeriousFirmaCraft modpack (modified personally)

**Comment by eerussianguy** [comment]
this is due to vexxel's resource pack
