### ISSUE TITLE
tfc book title incorrect

### ISSUE THREAD

**Issue by billyma6** [eerussianguy/firmalife#131]
in the in-game manual for TFC accessed from the inventory, the Differences from Classic entry has an error on the second page; the contents discuss breadmaking differences but the title is the same as the previous page, where cheesemaking differences were discussed

**Comment by Random-Cookie** [comment]
![2023-05-14_17 01 37](https://github.com/eerussianguy/firmalife/assets/11795182/9bc1e961-92fe-420e-a3a5-47ac788ef9e1)
Screenshot of the page in question (left).
Tracked to: https://github.com/eerussianguy/firmalife/blob/2127feb611756deeeccdc1fcca4e9cb1df965968/resources/generate_book.py#L54

**Comment by Random-Cookie** [comment]
Updated Page
![2023-05-14_17 52 23](https://github.com/eerussianguy/firmalife/assets/11795182/b2763875-2147-4262-bf17-d55d645e931d)
