### ISSUE TITLE
Crash on trying to carve pumpkin

### ISSUE THREAD

**Issue by Apot98** [eerussianguy/firmalife#137]
Crash Log: https://gist.github.com/Apot98/653f1c698bfc498a128d210793d77293
Minecraft Version: 1.18.2
Mods: 
TerraFirmaCraft-Forge-1.18.2-2.2.23
firmalife-1.2.12
curios-forge-1.18.2-5.0.9.0
Patchouli-1.18.2-71.1
jei-1.18.2-forge-10.2.1.1004

Game crashes on right-clicking with a pumpkin on hand and a knife in player's inventory, presumptively trying to carve the pumpkin.

**Comment by eerussianguy** [comment]
fixed
