### ISSUE TITLE
Cannot cast Chromium/Stainless Steel using Fire Ingot Molds

### ISSUE THREAD

**Issue by Nemo157** [eerussianguy/firmalife#140]
Each ingot type needs a duplicate casting recipe using a `tfc:ceramic/fire_ingot_mold`.

**Comment by eerussianguy** [comment]
fixed

**Comment by Nemo157** [comment]
A little mistake in the outputs:

https://github.com/eerussianguy/firmalife/blob/02a4514603bc7c6b051e6f1e901a0e12e6b2b482/src/main/resources/data/firmalife/recipes/casting/chromium_ingot_fire.json#L7-L13
