### ISSUE TITLE
Crash: java.lang.ArithmeticException: / by zero

### ISSUE THREAD

**Issue by dimon7147** [eerussianguy/firmalife#147]
Server crashes because of the com.eerussianguy.firmalife.common.blockentities.VatBlockEntity
Player says he was filling firmalife:vat using tfc:wooden_bucket with water, then it crashed.
Mod version: 1.2.13
Modpack: TerraFirmaCraft HardRock v0.3.5
Crast report: https://pastebin.com/7pci7ava

**Comment by eerussianguy** [comment]
fixed
