### ISSUE TITLE
Can eat whole raw/cooked pumpkin pie including pie pan

### ISSUE THREAD

**Issue by Nemo157** [eerussianguy/firmalife#148]
I was wondering why the cooked pumpkin pie gave no nutrition, but ate it anyway pan and all. Only afterwards did I realise that there was a crafting recipe to un-pan the pie giving something with nutrition and the pan back. Either the raw/cooked pumpkin pie items should be inedible, or the cooked version should have some nutrition and both should give the pan back when eaten.

**Comment by eerussianguy** [comment]
Let this be a lesson to not eat things with no nutrition.
