### ISSUE TITLE
Drying mat recipe timer resets and stops progressing after world loading

### ISSUE THREAD

**Issue by HermitOwO** [eerussianguy/firmalife#155]

**Comment by theLittleStone** [comment]
I reproduced this question in 1.18 ver ( 1.20 ver has not been tested yet). 
I guess this addition causes the bug: 
![2023-12-30_143248](https://github.com/eerussianguy/firmalife/assets/67592979/74f5d9c6-6ee4-4671-9550-ff3129c4a4a1)
This addition locates in : `src/main/java/com/eerussianguy/firmalife/common/blockentities/DryingMatBlockEntity.java`

**Comment by eerussianguy** [comment]
confirmed and fixed thanks
