### ISSUE TITLE
(2.0.9-beta) None of the Greenhouse Trapdoors Drop when Broken

### ISSUE THREAD

**Issue by TimeBender25** [eerussianguy/firmalife#160]
All of the variety of Greenhouse Trapdoors do not have a loot table json file, and thus do not drop as an item when broken even with the appropriate tool

**Comment by MasterSloth1** [comment]
This is still an issue even with version
FirmaLife-1.20.1-2.1.0
upon looking in the loot tables they are there but they have a malformed item string name (the item name is missing the mod ID)
https://github.com/eerussianguy/firmalife/blob/bb9037bcc512a34c54afaeba7b1ddae425655263/src/main/resources/data/firmalife/loot_tables/blocks/copper_greenhouse_trapdoor.json#L11

it is like this on all trapdoors.
