### ISSUE TITLE
Firmalife failed to load correctly with the latest version of TFC

### ISSUE THREAD

**Issue by CaveNJ** [eerussianguy/firmalife#161]
Here are some logs for the crash with only TFC and firmalife installed

[firmalife_tfc_update_crash_log.txt](https://github.com/eerussianguy/firmalife/files/14900112/firmalife_tfc_update_crash_log.txt)
[firmalife_tfc_update_crash-latest.log](https://github.com/eerussianguy/firmalife/files/14900113/firmalife_tfc_update_crash-latest.log)

**Comment by sheldingo** [comment]
Had the same issue as you, if you are on the latest version of terrafirmcraft (1.20.1 - **3.2.0**) rolling it back to the previous version (1.20.1 - **3.1.9**) seems to fix the issue.

**Comment by WaterWolf5918** [comment]
> Had the same issue as you, if you are on the latest version of terrafirmcraft (1.20.1 - **3.2.0**) rolling it back to the previous version (1.20.1 - **3.1.9**) seems to fix the issue.

Fix worked for me. Thanks
