### ISSUE TITLE
Eating a pumpkin pie eats the pan

### ISSUE THREAD

**Issue by 6TELOIV** [eerussianguy/firmalife#163]
As the title says, eating the pumpkin pie consumes the pan. I don't see a way around this in-game, the only options are to compost it or  wash it in a barrel. It doesn't seem intended like TFC's jars loosing their lids. I know my character needs iron but not a pans-worth

Possible duplicate of https://github.com/eerussianguy/firmalife/issues/148 but this happens with the cooked pumpkin pie.

**Comment by eerussianguy** [comment]
fixed... at long last
