### ISSUE TITLE
Chromite is too common, should be configurable

### ISSUE THREAD

**Issue by yorkeJohn** [eerussianguy/firmalife#165]
After doing some testing with the `clearworld` command, I have noticed that chromite is far too common, especially since it only has an extremely niche use case. Its spawn rate should be lower, or at least configurable. Just clearing a 50 block radius revealed 6 massive deposits- way too much.

**Comment by eerussianguy** [comment]
Its configurable lol. but yes it's been tweaked on newer versions and i'll continue to tweak it.

**Comment by yorkeJohn** [comment]
Where is it configurable? I am not getting a generated firmalife config at all.
