### ISSUE TITLE
All food has same hunger value

### ISSUE THREAD

**Issue by Proxwian** [eerussianguy/firmalife#168]
![image](https://github.com/user-attachments/assets/43115462-6ab5-4427-b3c3-176bde4f9774)
![image](https://github.com/user-attachments/assets/f16325f1-a50f-404e-b008-edfb8f0c28a3)
![image](https://github.com/user-attachments/assets/466a9317-a61c-424a-ad7a-aac010eb34d8)

It seems unreal that main food/farmer addon for TFC has this issue. Am I doing something wrong? Forge 1.20.1

**Comment by MrHiTech123** [comment]
I'd assume this mod is using the food's vanilla food value, not its TFC food value, so that's normal. TFC food value is data-driven and whatever mod you're using probably is checking the vanilla food value. This is the same for all Firmalife foods.

What mod is it?

**Comment by eerussianguy** [comment]
closing based on lack of info
