### ISSUE TITLE
The barrel remains after crafting stomping barrel

### ISSUE THREAD

**Issue by MAKKOVbulka** [eerussianguy/firmalife#170]
I accidentally noticed during the game that the stomping barrel recipe does not work correctly, after crafting the barrel remains, although logically it should disappear. I tried to fix it myself, but I'm not that good at it.
https://github.com/user-attachments/assets/3c61a85d-5add-4db2-9632-30fdb2879973

**Comment by eerussianguy** [comment]
i think i fixed this
