### ISSUE TITLE
Any Firmalife Dough not baking except Oven

### ISSUE THREAD

**Issue by wandperson** [eerussianguy/firmalife#171]
In the Patchouli book in section "Bread" said "Dough can be cooked like normal to produce Bread!".

But, any Firmalife dough (even filled pizza or pie) can't be cooked on any sources except Oven.
Firepit, Grill (on Oven too), Charcoal Pit, these all just heat up Dough and nothing changing over time.

Versions: 2.1.8 - 2.1.9

**Comment by eerussianguy** [comment]
Oven is required
