### ISSUE TITLE
Uninsulated Top Ovens causing inconsistent cooking behaviour

### ISSUE THREAD

**Issue by JotredDev** [eerussianguy/firmalife#173]
Bug:
With an uninsulated Top Oven, the items put in to bake don't start baking in a consistent way

Expected Behaviour:
Despite the Top Oven being uninsulated, the items should all start cooking at the same time, once the Top Oven reaches baking temperature

Replication Process:

Start with an uninsulated oven (here with an insulated one for comparison)
![2024-10-20_10 04 15](https://github.com/user-attachments/assets/c313acc7-450b-4467-9e4c-26aa91ab5859)

Put in an item that can be baked in the oven (here: Oat Dough, not depicted are the hickory logs used as fuel)
![2024-10-20_10 05 47](https://github.com/user-attachments/assets/f6cd0efe-1bd8-474e-85ad-0f0141ba1999)

Once the Bottom Oven is lit, the Top Oven slowly heats up. Only one of the items actually starts baking
![2024-10-20_10 08 04](https://github.com/user-attachments/assets/e6d51898-77aa-4a55-ab34-23df8762253e)

Only after the first item has finished baking, the others start baking
![2024-10-20_09 58 19](https://github.com/user-attachments/assets/e1f5c741-c085-4e72-bcb6-9f9e6348e769)

However, after some (not consistent) amount of time, those other items stop baking again (depicted: two attempts, right after the items stopped baking, to show time discrepancies)
![2024-10-20_09 58 33](https://github.com/user-attachments/assets/6481e74a-9d66-4162-8c32-3e22bae1f881)
![2024-10-20_10 13 01](https://github.com/user-attachments/assets/c106c0c5-502f-4b7d-973c-a74cd7d58d01)

Once the item that was in the spot of the first item that got baked is removed (here by letting it burn up in the oven), the other items actually start fully baking to completion
![2024-10-20_10 16 31](https://github.com/user-attachments/assets/c589121c-f292-4a21-990c-bafcfb249da7)

However, once they are done, they never start burning up
![2024-10-20_10 23 03](https://github.com/user-attachments/assets/47f61482-9fca-49e7-84e4-da06b68c66ee)

This was tested with:
Firmalife-1.20.1-2.1.11
Jade-1.20.1-forge-11.11.1
Patchouli-1.20.1-84-FORGE
TerraFirmaCraft-Forge-1.20.1-3.2.7

**Comment by BadsyEdgecat** [comment]
i can confirm that this happens in other instances of the game, including the version used in the pack Gravitas 2

**Comment by eerussianguy** [comment]
fixed
