### ISSUE TITLE
X-Ray Glitch with Nutritive Basin

### ISSUE THREAD

**Issue by AnnaLycoris** [eerussianguy/firmalife#174]
Observed Behaviour: Blocks behind the basin are not rendered through the glass panel until the nearest non-opaque block
Expected Behaviour: The basin's glass panel behaves like a regular glass block
Steps to reproduce: Place down a nutritive basin

Possible cause: The nutritive basin itself is not considered a non-opaque block, or uses a block model that is considered opaque.

Bug observed in **firmalife-1.2.18.jar**

Screenshot:
![image](https://github.com/user-attachments/assets/91f08d53-a8a1-46e9-a568-33ed10018062)

Notes: This bug was observed in a modpack. Due to the ease of reproduction, I decided to report it anyway.

**Comment by quiltedhills** [comment]
some extra info:
this seems to be an issue with embeddium/rubidium breaking the rendering for nutritive basins and toggling this specific feature on seems to fix it!
![image](https://github.com/user-attachments/assets/133a7152-6e6b-48e0-bc07-2530b1ce8739)

the textures are rendered correctly if embeddium/rubidium is not present

**Comment by eerussianguy** [comment]
while unfortunate i will not be updating 1.18 for something like this
