### ISSUE TITLE
[Suggestion]: Change to How the Oven is Made

### ISSUE THREAD

**Issue by MythrilBagels** [eerussianguy/firmalife#181]
Hi! I want to preface by saying that I've been really enjoying playing around with Firmalife, its added so much to my TFC experience, the more in-depth cooking, the winemaking, the greenhouse + cellar systems, etc, they're all so cool!
However, one of the things that I've noticed that has been bothering me is that the method of creating an oven feels particularly out of place compared to other things in this and the base mod. For instance, I feel that shaping the clay into the oven blocks themselves and then firing them doesn't make much sense given that they are visually regular brick ovens. I wouldn't mind this particular method if it were for an earthen oven instead, but I also really enjoy the aesthetic of a building a rustic brick oven (compared to the Finishes mechanic, which I don't entirely believe is necessary).

The main way I would suggest making this feel more natural could be to craft the blocks directly using already-fired bricks. I feel it would be beneficial to have them made this way because it mirrors how real brick ovens are made!
### Bottom Oven
Using brick blocks for the walls, and single bricks for the cooking surface.
![image](https://github.com/user-attachments/assets/a61b9d19-bc6f-4180-8e10-62cdb8f0d9c3)
(Could possibly be renamed to "Stove", since its usage with the vat sort of points that way.)
### Top Oven
![image](https://github.com/user-attachments/assets/d9b9dcfb-dccf-4c36-b7a7-7e76738cab9a)
(brick leggings lol)
### Chimney
![image](https://github.com/user-attachments/assets/391b3d3c-f831-4919-85bd-c44aca47f8f5)

Please understand that my nitpicking comes from a place of respect and passion, my only goal is to share feedback that I believe could be beneficial to the mod.
Overall, I appreciate hard work you've put into these projects and I'm excited to see how they will evolve in the future!
Thank you for your time.

**Comment by MythrilBagels** [comment]
I forgot to finish the title oops, i dont think i can change it...
pretend it says "[Suggestion]: Change to How the Oven is Made"

**Comment by Sigmenzzz** [comment]
In fact, you can write them into a datapack or even a simple mod as addon.
It'll be easy, and it's unnecessary to give up the original way, others can choose the way they love.

**Comment by MythrilBagels** [comment]
While I understand that this sort of change could easily be made with a datapack, I feel it would be more beneficial to include in the mod itself.
To reiterate my point on why I believe the current system doesn't fit within the mod; The recipe stands out as inconsistent with other brick products, with it being made in the same way as raw clay products instead.
Like I also suggested, the unique firing system could still be in place as an earthen oven made of mud/clay/daub as an earlier option, while the classic brick oven made with plain brick, both of which are realistic methods of building an oven and make sense given the setting. This way, both systems are kept, and players get a new primitive form of an oven for their builds!
Overall, I believe it could be a great change, and I would love to see it happen

**Comment by eerussianguy** [comment]
Feel free to use discord for suggestions
