### ISSUE TITLE
Constant crashes without Caffeine addon

### ISSUE THREAD

**Issue by Lebeg134** [eerussianguy/firmalife#31]
For some reason the mod always crashes if Caffeine addon is not installed
I always used the newest TFC version available (...173)
Crash logs:
https://pastebin.com/nX3zNPbA
https://pastebin.com/wj5ZTRkd
https://pastebin.com/LKCEv1Nk
(All 3 crashes are diferent with different mods enabled)

**Comment by eerussianguy** [comment]
The caffeine addon is broken, you can't use it with anything. Also this looks like you might have accidentally downloaded the 'sources' jar instead of the regular jar?
