### ISSUE TITLE
Crash on completion of greenhouse

### ISSUE THREAD

**Issue by Sumguy62** [eerussianguy/firmalife#41]
I missed a couple of windows, and a tick or so after putting them in, the game crashed to the crash screen.

[crash-2021-04-05_23.26.38-server.txt](https://github.com/eerussianguy/firmalife/files/6261867/crash-2021-04-05_23.26.38-server.txt)

**Comment by eerussianguy** [comment]
Second person to report this. appears to be some sort of edge case
