### ISSUE TITLE
How to get Rennet ?

### ISSUE THREAD

**Issue by frostmoonsay** [eerussianguy/firmalife#47]
I can't get any rennet when I killing a cow or deer, maybe I got the wrong way. But how can I get the rennet, I can't find the way in wiki either. Is this function not completed yet?

**Comment by eerussianguy** [comment]
it's a 1/3 chance

**Comment by eerussianguy** [comment]
i will make it 100% chance next update

**Comment by frostmoonsay** [comment]
I've killed over 50 cows and still haven't dropped rennet.
