### ISSUE TITLE
mallets textures

### ISSUE THREAD

**Issue by Tavarnarmo** [eerussianguy/firmalife#48]
Not sure if this is an issue or just not implemented yet, but only part of mallets have proper textures ;)

**Comment by eerussianguy** [comment]
I have provided textures for all the TFC mallets. Ask the authors of the addon mods to add support

**Comment by Tavarnarmo** [comment]
erm but the mallets without texture are tfc mallets, the other ones are ok

**Comment by eerussianguy** [comment]
That doesn't make any sense. can you send a photo?

**Comment by Tavarnarmo** [comment]
![mallet](https://user-images.githubusercontent.com/30972736/114896738-ded37f00-9e10-11eb-9b51-531b4ef4364f.png)

**Comment by eerussianguy** [comment]
Yeah you're playing with tfc metallum, like I said. Ask them what they're doing

**Comment by Tavarnarmo** [comment]
Huh I tried few testing worlds and looks like this is rather issue with TFCompat. Strange xD Anyway made a ticket there :)
