### ISSUE TITLE
Mallets should go on tool racks

### ISSUE THREAD

**Issue by Gaelmare** [eerussianguy/firmalife#59]
don't recall what's required, sorry.

**Comment by eerussianguy** [comment]
They should already go on them based on this commit
https://github.com/TerraFirmaCraft/TerraFirmaCraft/commit/917de5158ad261852accbcbbcb2d5280c6409075

**Comment by eerussianguy** [comment]
Seems goofy...

**Comment by eerussianguy** [comment]
In my testing it seems to work. More info needed
