### ISSUE TITLE
Bug displaying the amount of metal during casting

### ISSUE THREAD

**Issue by SpeeeDCraft** [eerussianguy/firmalife#63]
1. Take and heat dust in a small vessel, for example bismuth bronze.
2. Wait until it melts into liquid.
3. Take it to the inventory.
4. Open the small vessel menu.
5. Put the mallet form in this gui.
6. Hover over the form.
Problem: although the mold will be filled with metal, but the metal indicator of the mallet mold will show 1 units.

**Comment by eerussianguy** [comment]
Unfortunately the mold code is a bit beyond me, and this isn't a game breaking bug, so we're going to have to let this one go
