### ISSUE TITLE
[1.18.2] Right clicking a beehive doesn't cancel the right click action properly

### ISSUE THREAD

**Issue by SvenParoth** [eerussianguy/firmalife#67]
If you are holding an item that can be used, such as a bowl of food when you are hungry, and right click the beehive, the beehive UI opens but your character still continues to eat the soup, as if you are holding down right click. 

Tested in firmalife 1.0.3-alpha

**Comment by eerussianguy** [comment]
does this persist on build 4?

**Comment by Ironcanon** [comment]
Just tested on latest build 1.1.1 and seems to be fixed
