### ISSUE TITLE
Taking an item out of the drying mat visual duplicates the item in player inventory and on mat

### ISSUE THREAD

**Issue by Ironcanon** [eerussianguy/firmalife#71]
Shift-right clicking the drying mat when it has an item on it causes the player to get the item in the drying mat but doesn't remove the item visually from the drying mat. Shift-right clicking the mat again causes the player to visually get another item (if the item isn't the result of a drying recipe. If it is then the player doesn't get the ghost item), however that item disapears once the item stack is moved in the inventory.

Steps to replicate.
1. Place a drying mat under the sky.
2. Place a snowberry onto the drying mat.
3. Shift-right click the mat and see that the berry is still on the mat but the player has recived the berry back
4. Shift-right click the mat again and see the player get another berry
5. Move the berry stack and see the number of berries reduce back to 1

**Comment by eerussianguy** [comment]
Does this occur on the last curse release (which I haven’t released on
GitHub yet)

**Comment by Ironcanon** [comment]
Yes, this occurs on build 1.1.1
