### ISSUE TITLE
[1.18.2] Repeated Crash On Hive Open

### ISSUE THREAD

**Issue by Poragon** [eerussianguy/firmalife#72]
Experienced on a server running this [modpack](https://www.curseforge.com/minecraft/modpacks/tfc-bits-and-bobs/files), Firmalife beta 1.1.1

Opening a newly placed hive resulted in a crash a few seconds later, as well as the same crash repeating each time I attempt to join the server. A friend can join and approach the hive with no crash but has yet to attempt interaction with it for risk of also being trapped in the beeverse.

Log for crash here;
[Pastebin](https://pastebin.com/1KAnx4W3)

**Comment by Ironcanon** [comment]
@Poragon Seems to be an issue with the hoe overlay and the cached bees, as a temp fix you can get your friend to break the hive which should let you re-join
