### ISSUE TITLE
Beets turn into soup, not sugar

### ISSUE THREAD

**Issue by Raerios** [eerussianguy/firmalife#74]
The pot recipe for turning beets into sugar just makes a pot of soup, rather than the 3 sugar it's supposed to.

**Comment by Ironcanon** [comment]
@Raerios How many beets did you put into the pot? You need to specifically put in 5 beets for it to turn into sugar.

**Comment by Raerios** [comment]
I was using five beets

**Comment by eerussianguy** [comment]
I think I’m gonna require salt or some non-food item for it.
