### ISSUE TITLE
Empty Outputs for Food in JEI (Raw Pizza & Smoked Foods)

### ISSUE THREAD

**Issue by Joe-org** [eerussianguy/firmalife#80]
1)The "Smoking" Tab itself currently has no icon that represents it. While all outputs for smoking food do not appear.
![2022-09-09_02 40 14](https://user-images.githubusercontent.com/113080914/189361244-f980269b-4c3d-4371-a191-832396f8d9c9.png)

2)All variation recipes of "Raw Pizza" do not appear as an output.
![2022-09-09_14 26 53](https://user-images.githubusercontent.com/113080914/189362439-3a52e6fb-d0c6-4492-a0eb-120f0285d098.png)

**Comment by eerussianguy** [comment]
fixed for smoked foods in TFC
