### ISSUE TITLE
Leaf particles collision with all Roof Top Blocks

### ISSUE THREAD

**Issue by Joe-org** [eerussianguy/firmalife#85]
Leaf particles dont register all **Roof Top Blocks** as slabs, making the particles stop halfway and spazzing out, acting as if they're colliding with a full block instead.

https://user-images.githubusercontent.com/113080914/189972763-1ca7ffb1-9f0b-4db5-b74f-33c0eb5b78e3.mp4

**Comment by eerussianguy** [comment]
roof top blocks are slabs.
