### ISSUE TITLE
Metals unable to pour or pile

### ISSUE THREAD

**Issue by Notenoughmail** [eerussianguy/firmalife#94]
### Issue
Both chromium and stainless steel are unable to be poured into ingot molds nor are their ingot and sheet items able to be placed into ingot/sheet piles

### Environment
Forge 40.1.80
TFC 2.1.16
Firmalife 1.1.15
Patchouli 71.1

### Other Mods
None

**Comment by eerussianguy** [comment]
fixed in next build
