### ISSUE TITLE
Moisture transducer

### ISSUE THREAD

**Issue by MCChiter** [eerussianguy/firmalife#98]
There is no data in wiki or book on what it does, although you can make it and it can place pipes. I can only assume it replaces spouts and sprinklers mentioned in greenhouse wiki entry

Edit: i did poke around to see how could it possibly work and managed to, but it only works in the corner near the climate station?

**Comment by eerussianguy** [comment]
Yes it will be documented eventually. Please do not use this issue tracker for random questions
